name: Update dev image

on:
  schedule:
    - cron: '0 1 * * *'  # Run every day
  workflow_dispatch:

env:
  BRANCH: dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

    - name: Checkout code
      uses: actions/checkout@v7
      with:
        ref: ${{ env.BRANCH }}

    - name: Get latest Sage dev version
      run: |
        SAGE_VERSION=$(curl -s "https://hub.docker.com/v2/repositories/sagemath/sagemath/tags/?page_size=100" | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?\.(beta|rc)[0-9]+$' | sort -V | tail -n1)
        echo "SAGE_VERSION=$SAGE_VERSION" >> $GITHUB_ENV
        echo "PACKAGE_NAME=ghcr.io/${{ github.repository }}:$SAGE_VERSION" >> $GITHUB_ENV

    # Build and publish the base image to GHCR

    - name: Log in to the Container registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v7
      with:
        context: .github
        push: true
        tags: |
          ${{ env.PACKAGE_NAME }}
          ghcr.io/${{ github.repository }}:dev
        build-args: |
          TAG=${{ env.SAGE_VERSION }}

    # Update files for Binder

    - name: Update files for Binder
      run: |
        BINDER_PACKAGE="ghcr.io/${{ github.repository }}:dev"
        PACKAGE_NAME_ESCAPED=$(echo "${BINDER_PACKAGE}" | sed 's/\//\\\//g')
        sed -i "s/FROM \S*/FROM ${PACKAGE_NAME_ESCAPED}/g" Dockerfile
        sed -i "s/FROM \S*/FROM ${PACKAGE_NAME_ESCAPED}/g" README.rst
        git config --global user.email alice@wonderland
        git config --global user.name alice
        git add Dockerfile README.rst
        git diff --quiet && git diff --staged --quiet || git commit -m "Update Sage to ${{ env.SAGE_VERSION }}"
        git push origin ${{ env.BRANCH }}

    # Build docker image for Binder from Dockerfile at root

    - name: Binder build
      timeout-minutes: 30
      continue-on-error: true
      run: |
        curl --keepalive-time 600 -H "Accept: text/event-stream" -L https://mybinder.org/build/gh/sagemath/sage-binder-env/$BRANCH
